//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiciosDynamics.WebApi.WSIngresos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSIngresosSoap", Namespace="http://tempuri.org/")]
    public partial class WSIngresos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ingresosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresos_conceptosOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertHingresosOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertHingresos_ConceptosOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertHingresos_pagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteIngresosOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteIngresos_ConceptosOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteIngresos_pagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback countIngresos_conceptosOperationCompleted;
        
        private System.Threading.SendOrPostCallback countIngresos_pagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback countIngresosOperationCompleted;
        
        private System.Threading.SendOrPostCallback carrerasFaltantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback conceptosFaltantesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSIngresos() {
            this.Url = global::ServiciosDynamics.WebApi.Properties.Settings.Default.ServiciosDynamics_WebApi_WSIngresos_WSIngresos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ingresosCompletedEventHandler ingresosCompleted;
        
        /// <remarks/>
        public event ingresos_conceptosCompletedEventHandler ingresos_conceptosCompleted;
        
        /// <remarks/>
        public event insertHingresosCompletedEventHandler insertHingresosCompleted;
        
        /// <remarks/>
        public event insertHingresos_ConceptosCompletedEventHandler insertHingresos_ConceptosCompleted;
        
        /// <remarks/>
        public event insertHingresos_pagoCompletedEventHandler insertHingresos_pagoCompleted;
        
        /// <remarks/>
        public event deleteIngresosCompletedEventHandler deleteIngresosCompleted;
        
        /// <remarks/>
        public event deleteIngresos_ConceptosCompletedEventHandler deleteIngresos_ConceptosCompleted;
        
        /// <remarks/>
        public event deleteIngresos_pagoCompletedEventHandler deleteIngresos_pagoCompleted;
        
        /// <remarks/>
        public event countIngresos_conceptosCompletedEventHandler countIngresos_conceptosCompleted;
        
        /// <remarks/>
        public event countIngresos_pagoCompletedEventHandler countIngresos_pagoCompleted;
        
        /// <remarks/>
        public event countIngresosCompletedEventHandler countIngresosCompleted;
        
        /// <remarks/>
        public event carrerasFaltantesCompletedEventHandler carrerasFaltantesCompleted;
        
        /// <remarks/>
        public event conceptosFaltantesCompletedEventHandler conceptosFaltantesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ingresos(string _origen, string _fromDate, string _toDate) {
            object[] results = this.Invoke("ingresos", new object[] {
                        _origen,
                        _fromDate,
                        _toDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ingresosAsync(string _origen, string _fromDate, string _toDate) {
            this.ingresosAsync(_origen, _fromDate, _toDate, null);
        }
        
        /// <remarks/>
        public void ingresosAsync(string _origen, string _fromDate, string _toDate, object userState) {
            if ((this.ingresosOperationCompleted == null)) {
                this.ingresosOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresosOperationCompleted);
            }
            this.InvokeAsync("ingresos", new object[] {
                        _origen,
                        _fromDate,
                        _toDate}, this.ingresosOperationCompleted, userState);
        }
        
        private void OningresosOperationCompleted(object arg) {
            if ((this.ingresosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresosCompleted(this, new ingresosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresos_conceptos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ingresos_conceptos(string _recibo, string _fecha, string _tipo) {
            object[] results = this.Invoke("ingresos_conceptos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ingresos_conceptosAsync(string _recibo, string _fecha, string _tipo) {
            this.ingresos_conceptosAsync(_recibo, _fecha, _tipo, null);
        }
        
        /// <remarks/>
        public void ingresos_conceptosAsync(string _recibo, string _fecha, string _tipo, object userState) {
            if ((this.ingresos_conceptosOperationCompleted == null)) {
                this.ingresos_conceptosOperationCompleted = new System.Threading.SendOrPostCallback(this.Oningresos_conceptosOperationCompleted);
            }
            this.InvokeAsync("ingresos_conceptos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo}, this.ingresos_conceptosOperationCompleted, userState);
        }
        
        private void Oningresos_conceptosOperationCompleted(object arg) {
            if ((this.ingresos_conceptosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresos_conceptosCompleted(this, new ingresos_conceptosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertHingresos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertHingresos(string _recibo, string _fecha, string _tipo) {
            object[] results = this.Invoke("insertHingresos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertHingresosAsync(string _recibo, string _fecha, string _tipo) {
            this.insertHingresosAsync(_recibo, _fecha, _tipo, null);
        }
        
        /// <remarks/>
        public void insertHingresosAsync(string _recibo, string _fecha, string _tipo, object userState) {
            if ((this.insertHingresosOperationCompleted == null)) {
                this.insertHingresosOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertHingresosOperationCompleted);
            }
            this.InvokeAsync("insertHingresos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo}, this.insertHingresosOperationCompleted, userState);
        }
        
        private void OninsertHingresosOperationCompleted(object arg) {
            if ((this.insertHingresosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertHingresosCompleted(this, new insertHingresosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertHingresos_Conceptos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertHingresos_Conceptos(string _recibo, string _fecha, string _tipo) {
            object[] results = this.Invoke("insertHingresos_Conceptos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertHingresos_ConceptosAsync(string _recibo, string _fecha, string _tipo) {
            this.insertHingresos_ConceptosAsync(_recibo, _fecha, _tipo, null);
        }
        
        /// <remarks/>
        public void insertHingresos_ConceptosAsync(string _recibo, string _fecha, string _tipo, object userState) {
            if ((this.insertHingresos_ConceptosOperationCompleted == null)) {
                this.insertHingresos_ConceptosOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertHingresos_ConceptosOperationCompleted);
            }
            this.InvokeAsync("insertHingresos_Conceptos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo}, this.insertHingresos_ConceptosOperationCompleted, userState);
        }
        
        private void OninsertHingresos_ConceptosOperationCompleted(object arg) {
            if ((this.insertHingresos_ConceptosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertHingresos_ConceptosCompleted(this, new insertHingresos_ConceptosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertHingresos_pago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertHingresos_pago(string _recibo, string _fecha, string _tipo) {
            object[] results = this.Invoke("insertHingresos_pago", new object[] {
                        _recibo,
                        _fecha,
                        _tipo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertHingresos_pagoAsync(string _recibo, string _fecha, string _tipo) {
            this.insertHingresos_pagoAsync(_recibo, _fecha, _tipo, null);
        }
        
        /// <remarks/>
        public void insertHingresos_pagoAsync(string _recibo, string _fecha, string _tipo, object userState) {
            if ((this.insertHingresos_pagoOperationCompleted == null)) {
                this.insertHingresos_pagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertHingresos_pagoOperationCompleted);
            }
            this.InvokeAsync("insertHingresos_pago", new object[] {
                        _recibo,
                        _fecha,
                        _tipo}, this.insertHingresos_pagoOperationCompleted, userState);
        }
        
        private void OninsertHingresos_pagoOperationCompleted(object arg) {
            if ((this.insertHingresos_pagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertHingresos_pagoCompleted(this, new insertHingresos_pagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteIngresos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteIngresos(string _recibo, string _fecha, string _tipo) {
            object[] results = this.Invoke("deleteIngresos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteIngresosAsync(string _recibo, string _fecha, string _tipo) {
            this.deleteIngresosAsync(_recibo, _fecha, _tipo, null);
        }
        
        /// <remarks/>
        public void deleteIngresosAsync(string _recibo, string _fecha, string _tipo, object userState) {
            if ((this.deleteIngresosOperationCompleted == null)) {
                this.deleteIngresosOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteIngresosOperationCompleted);
            }
            this.InvokeAsync("deleteIngresos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo}, this.deleteIngresosOperationCompleted, userState);
        }
        
        private void OndeleteIngresosOperationCompleted(object arg) {
            if ((this.deleteIngresosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteIngresosCompleted(this, new deleteIngresosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteIngresos_Conceptos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteIngresos_Conceptos(string _recibo, string _fecha, string _tipo) {
            object[] results = this.Invoke("deleteIngresos_Conceptos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteIngresos_ConceptosAsync(string _recibo, string _fecha, string _tipo) {
            this.deleteIngresos_ConceptosAsync(_recibo, _fecha, _tipo, null);
        }
        
        /// <remarks/>
        public void deleteIngresos_ConceptosAsync(string _recibo, string _fecha, string _tipo, object userState) {
            if ((this.deleteIngresos_ConceptosOperationCompleted == null)) {
                this.deleteIngresos_ConceptosOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteIngresos_ConceptosOperationCompleted);
            }
            this.InvokeAsync("deleteIngresos_Conceptos", new object[] {
                        _recibo,
                        _fecha,
                        _tipo}, this.deleteIngresos_ConceptosOperationCompleted, userState);
        }
        
        private void OndeleteIngresos_ConceptosOperationCompleted(object arg) {
            if ((this.deleteIngresos_ConceptosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteIngresos_ConceptosCompleted(this, new deleteIngresos_ConceptosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteIngresos_pago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteIngresos_pago(string _recibo, string _fecha, string _tipo) {
            object[] results = this.Invoke("deleteIngresos_pago", new object[] {
                        _recibo,
                        _fecha,
                        _tipo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteIngresos_pagoAsync(string _recibo, string _fecha, string _tipo) {
            this.deleteIngresos_pagoAsync(_recibo, _fecha, _tipo, null);
        }
        
        /// <remarks/>
        public void deleteIngresos_pagoAsync(string _recibo, string _fecha, string _tipo, object userState) {
            if ((this.deleteIngresos_pagoOperationCompleted == null)) {
                this.deleteIngresos_pagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteIngresos_pagoOperationCompleted);
            }
            this.InvokeAsync("deleteIngresos_pago", new object[] {
                        _recibo,
                        _fecha,
                        _tipo}, this.deleteIngresos_pagoOperationCompleted, userState);
        }
        
        private void OndeleteIngresos_pagoOperationCompleted(object arg) {
            if ((this.deleteIngresos_pagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteIngresos_pagoCompleted(this, new deleteIngresos_pagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/countIngresos_conceptos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int countIngresos_conceptos(string _origen, string _fromDate, string _toDate) {
            object[] results = this.Invoke("countIngresos_conceptos", new object[] {
                        _origen,
                        _fromDate,
                        _toDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void countIngresos_conceptosAsync(string _origen, string _fromDate, string _toDate) {
            this.countIngresos_conceptosAsync(_origen, _fromDate, _toDate, null);
        }
        
        /// <remarks/>
        public void countIngresos_conceptosAsync(string _origen, string _fromDate, string _toDate, object userState) {
            if ((this.countIngresos_conceptosOperationCompleted == null)) {
                this.countIngresos_conceptosOperationCompleted = new System.Threading.SendOrPostCallback(this.OncountIngresos_conceptosOperationCompleted);
            }
            this.InvokeAsync("countIngresos_conceptos", new object[] {
                        _origen,
                        _fromDate,
                        _toDate}, this.countIngresos_conceptosOperationCompleted, userState);
        }
        
        private void OncountIngresos_conceptosOperationCompleted(object arg) {
            if ((this.countIngresos_conceptosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.countIngresos_conceptosCompleted(this, new countIngresos_conceptosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/countIngresos_pago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int countIngresos_pago(string _origen, string _fromDate, string _toDate) {
            object[] results = this.Invoke("countIngresos_pago", new object[] {
                        _origen,
                        _fromDate,
                        _toDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void countIngresos_pagoAsync(string _origen, string _fromDate, string _toDate) {
            this.countIngresos_pagoAsync(_origen, _fromDate, _toDate, null);
        }
        
        /// <remarks/>
        public void countIngresos_pagoAsync(string _origen, string _fromDate, string _toDate, object userState) {
            if ((this.countIngresos_pagoOperationCompleted == null)) {
                this.countIngresos_pagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncountIngresos_pagoOperationCompleted);
            }
            this.InvokeAsync("countIngresos_pago", new object[] {
                        _origen,
                        _fromDate,
                        _toDate}, this.countIngresos_pagoOperationCompleted, userState);
        }
        
        private void OncountIngresos_pagoOperationCompleted(object arg) {
            if ((this.countIngresos_pagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.countIngresos_pagoCompleted(this, new countIngresos_pagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/countIngresos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int countIngresos(string _origen, string _fromDate, string _toDate) {
            object[] results = this.Invoke("countIngresos", new object[] {
                        _origen,
                        _fromDate,
                        _toDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void countIngresosAsync(string _origen, string _fromDate, string _toDate) {
            this.countIngresosAsync(_origen, _fromDate, _toDate, null);
        }
        
        /// <remarks/>
        public void countIngresosAsync(string _origen, string _fromDate, string _toDate, object userState) {
            if ((this.countIngresosOperationCompleted == null)) {
                this.countIngresosOperationCompleted = new System.Threading.SendOrPostCallback(this.OncountIngresosOperationCompleted);
            }
            this.InvokeAsync("countIngresos", new object[] {
                        _origen,
                        _fromDate,
                        _toDate}, this.countIngresosOperationCompleted, userState);
        }
        
        private void OncountIngresosOperationCompleted(object arg) {
            if ((this.countIngresosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.countIngresosCompleted(this, new countIngresosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/carrerasFaltantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet carrerasFaltantes(string _origen, string _fromDate, string _toDate) {
            object[] results = this.Invoke("carrerasFaltantes", new object[] {
                        _origen,
                        _fromDate,
                        _toDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void carrerasFaltantesAsync(string _origen, string _fromDate, string _toDate) {
            this.carrerasFaltantesAsync(_origen, _fromDate, _toDate, null);
        }
        
        /// <remarks/>
        public void carrerasFaltantesAsync(string _origen, string _fromDate, string _toDate, object userState) {
            if ((this.carrerasFaltantesOperationCompleted == null)) {
                this.carrerasFaltantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncarrerasFaltantesOperationCompleted);
            }
            this.InvokeAsync("carrerasFaltantes", new object[] {
                        _origen,
                        _fromDate,
                        _toDate}, this.carrerasFaltantesOperationCompleted, userState);
        }
        
        private void OncarrerasFaltantesOperationCompleted(object arg) {
            if ((this.carrerasFaltantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.carrerasFaltantesCompleted(this, new carrerasFaltantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/conceptosFaltantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet conceptosFaltantes(string _origen, string _fromDate, string _toDate) {
            object[] results = this.Invoke("conceptosFaltantes", new object[] {
                        _origen,
                        _fromDate,
                        _toDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void conceptosFaltantesAsync(string _origen, string _fromDate, string _toDate) {
            this.conceptosFaltantesAsync(_origen, _fromDate, _toDate, null);
        }
        
        /// <remarks/>
        public void conceptosFaltantesAsync(string _origen, string _fromDate, string _toDate, object userState) {
            if ((this.conceptosFaltantesOperationCompleted == null)) {
                this.conceptosFaltantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconceptosFaltantesOperationCompleted);
            }
            this.InvokeAsync("conceptosFaltantes", new object[] {
                        _origen,
                        _fromDate,
                        _toDate}, this.conceptosFaltantesOperationCompleted, userState);
        }
        
        private void OnconceptosFaltantesOperationCompleted(object arg) {
            if ((this.conceptosFaltantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.conceptosFaltantesCompleted(this, new conceptosFaltantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ingresosCompletedEventHandler(object sender, ingresosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ingresosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ingresosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ingresos_conceptosCompletedEventHandler(object sender, ingresos_conceptosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ingresos_conceptosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ingresos_conceptosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertHingresosCompletedEventHandler(object sender, insertHingresosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertHingresosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertHingresosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertHingresos_ConceptosCompletedEventHandler(object sender, insertHingresos_ConceptosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertHingresos_ConceptosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertHingresos_ConceptosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertHingresos_pagoCompletedEventHandler(object sender, insertHingresos_pagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertHingresos_pagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertHingresos_pagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteIngresosCompletedEventHandler(object sender, deleteIngresosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteIngresosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteIngresosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteIngresos_ConceptosCompletedEventHandler(object sender, deleteIngresos_ConceptosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteIngresos_ConceptosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteIngresos_ConceptosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteIngresos_pagoCompletedEventHandler(object sender, deleteIngresos_pagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteIngresos_pagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteIngresos_pagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void countIngresos_conceptosCompletedEventHandler(object sender, countIngresos_conceptosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class countIngresos_conceptosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal countIngresos_conceptosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void countIngresos_pagoCompletedEventHandler(object sender, countIngresos_pagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class countIngresos_pagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal countIngresos_pagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void countIngresosCompletedEventHandler(object sender, countIngresosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class countIngresosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal countIngresosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void carrerasFaltantesCompletedEventHandler(object sender, carrerasFaltantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class carrerasFaltantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal carrerasFaltantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void conceptosFaltantesCompletedEventHandler(object sender, conceptosFaltantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class conceptosFaltantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal conceptosFaltantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591