//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiciosDynamics.WebApi.WSFacturas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSFacturasSoap", Namespace="http://galileo.edu/dynamicsax/facturas")]
    public partial class WSFacturas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback agregarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoBancariaDocenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback validaEsDocenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoPagoFacturacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoPagoDetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertHpagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertHpagosUgaDetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletePagosUgaDetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletePagosUgaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSFacturas() {
            this.Url = global::ServiciosDynamics.WebApi.Properties.Settings.Default.ServiciosDynamics_WebApi_WSFacturas_WSFacturas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event agregarFacturaCompletedEventHandler agregarFacturaCompleted;
        
        /// <remarks/>
        public event validarFacturaCompletedEventHandler validarFacturaCompleted;
        
        /// <remarks/>
        public event infoBancariaDocenteCompletedEventHandler infoBancariaDocenteCompleted;
        
        /// <remarks/>
        public event validaEsDocenteCompletedEventHandler validaEsDocenteCompleted;
        
        /// <remarks/>
        public event infoPagoFacturacionCompletedEventHandler infoPagoFacturacionCompleted;
        
        /// <remarks/>
        public event infoPagoDetalleCompletedEventHandler infoPagoDetalleCompleted;
        
        /// <remarks/>
        public event insertHpagosCompletedEventHandler insertHpagosCompleted;
        
        /// <remarks/>
        public event insertHpagosUgaDetalleCompletedEventHandler insertHpagosUgaDetalleCompleted;
        
        /// <remarks/>
        public event deletePagosUgaDetalleCompletedEventHandler deletePagosUgaDetalleCompleted;
        
        /// <remarks/>
        public event deletePagosUgaCompletedEventHandler deletePagosUgaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/agregarFactura", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string agregarFactura(string _proveedor, string _facturaserie, string _facturanumero, string _fechafactura, string _descripcion, decimal _monto, string _iddetalle, int _typeStaff, string _usuariooracle, string _noTramite) {
            object[] results = this.Invoke("agregarFactura", new object[] {
                        _proveedor,
                        _facturaserie,
                        _facturanumero,
                        _fechafactura,
                        _descripcion,
                        _monto,
                        _iddetalle,
                        _typeStaff,
                        _usuariooracle,
                        _noTramite});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void agregarFacturaAsync(string _proveedor, string _facturaserie, string _facturanumero, string _fechafactura, string _descripcion, decimal _monto, string _iddetalle, int _typeStaff, string _usuariooracle, string _noTramite) {
            this.agregarFacturaAsync(_proveedor, _facturaserie, _facturanumero, _fechafactura, _descripcion, _monto, _iddetalle, _typeStaff, _usuariooracle, _noTramite, null);
        }
        
        /// <remarks/>
        public void agregarFacturaAsync(string _proveedor, string _facturaserie, string _facturanumero, string _fechafactura, string _descripcion, decimal _monto, string _iddetalle, int _typeStaff, string _usuariooracle, string _noTramite, object userState) {
            if ((this.agregarFacturaOperationCompleted == null)) {
                this.agregarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarFacturaOperationCompleted);
            }
            this.InvokeAsync("agregarFactura", new object[] {
                        _proveedor,
                        _facturaserie,
                        _facturanumero,
                        _fechafactura,
                        _descripcion,
                        _monto,
                        _iddetalle,
                        _typeStaff,
                        _usuariooracle,
                        _noTramite}, this.agregarFacturaOperationCompleted, userState);
        }
        
        private void OnagregarFacturaOperationCompleted(object arg) {
            if ((this.agregarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarFacturaCompleted(this, new agregarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/validarFactura", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validarFactura(string _proveedor, string _facturaserie, string _facturanumero) {
            object[] results = this.Invoke("validarFactura", new object[] {
                        _proveedor,
                        _facturaserie,
                        _facturanumero});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validarFacturaAsync(string _proveedor, string _facturaserie, string _facturanumero) {
            this.validarFacturaAsync(_proveedor, _facturaserie, _facturanumero, null);
        }
        
        /// <remarks/>
        public void validarFacturaAsync(string _proveedor, string _facturaserie, string _facturanumero, object userState) {
            if ((this.validarFacturaOperationCompleted == null)) {
                this.validarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarFacturaOperationCompleted);
            }
            this.InvokeAsync("validarFactura", new object[] {
                        _proveedor,
                        _facturaserie,
                        _facturanumero}, this.validarFacturaOperationCompleted, userState);
        }
        
        private void OnvalidarFacturaOperationCompleted(object arg) {
            if ((this.validarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarFacturaCompleted(this, new validarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/infoBancariaDocente", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable infoBancariaDocente(string _codpers) {
            object[] results = this.Invoke("infoBancariaDocente", new object[] {
                        _codpers});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void infoBancariaDocenteAsync(string _codpers) {
            this.infoBancariaDocenteAsync(_codpers, null);
        }
        
        /// <remarks/>
        public void infoBancariaDocenteAsync(string _codpers, object userState) {
            if ((this.infoBancariaDocenteOperationCompleted == null)) {
                this.infoBancariaDocenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoBancariaDocenteOperationCompleted);
            }
            this.InvokeAsync("infoBancariaDocente", new object[] {
                        _codpers}, this.infoBancariaDocenteOperationCompleted, userState);
        }
        
        private void OninfoBancariaDocenteOperationCompleted(object arg) {
            if ((this.infoBancariaDocenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoBancariaDocenteCompleted(this, new infoBancariaDocenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/validaEsDocente", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validaEsDocente(string _codpers) {
            object[] results = this.Invoke("validaEsDocente", new object[] {
                        _codpers});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validaEsDocenteAsync(string _codpers) {
            this.validaEsDocenteAsync(_codpers, null);
        }
        
        /// <remarks/>
        public void validaEsDocenteAsync(string _codpers, object userState) {
            if ((this.validaEsDocenteOperationCompleted == null)) {
                this.validaEsDocenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidaEsDocenteOperationCompleted);
            }
            this.InvokeAsync("validaEsDocente", new object[] {
                        _codpers}, this.validaEsDocenteOperationCompleted, userState);
        }
        
        private void OnvalidaEsDocenteOperationCompleted(object arg) {
            if ((this.validaEsDocenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validaEsDocenteCompleted(this, new validaEsDocenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/infoPagoFacturacion", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable infoPagoFacturacion(string _origen, string _fecha) {
            object[] results = this.Invoke("infoPagoFacturacion", new object[] {
                        _origen,
                        _fecha});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void infoPagoFacturacionAsync(string _origen, string _fecha) {
            this.infoPagoFacturacionAsync(_origen, _fecha, null);
        }
        
        /// <remarks/>
        public void infoPagoFacturacionAsync(string _origen, string _fecha, object userState) {
            if ((this.infoPagoFacturacionOperationCompleted == null)) {
                this.infoPagoFacturacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoPagoFacturacionOperationCompleted);
            }
            this.InvokeAsync("infoPagoFacturacion", new object[] {
                        _origen,
                        _fecha}, this.infoPagoFacturacionOperationCompleted, userState);
        }
        
        private void OninfoPagoFacturacionOperationCompleted(object arg) {
            if ((this.infoPagoFacturacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoPagoFacturacionCompleted(this, new infoPagoFacturacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/infoPagoDetalle", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable infoPagoDetalle(string _nomina, string _correlativo) {
            object[] results = this.Invoke("infoPagoDetalle", new object[] {
                        _nomina,
                        _correlativo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void infoPagoDetalleAsync(string _nomina, string _correlativo) {
            this.infoPagoDetalleAsync(_nomina, _correlativo, null);
        }
        
        /// <remarks/>
        public void infoPagoDetalleAsync(string _nomina, string _correlativo, object userState) {
            if ((this.infoPagoDetalleOperationCompleted == null)) {
                this.infoPagoDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoPagoDetalleOperationCompleted);
            }
            this.InvokeAsync("infoPagoDetalle", new object[] {
                        _nomina,
                        _correlativo}, this.infoPagoDetalleOperationCompleted, userState);
        }
        
        private void OninfoPagoDetalleOperationCompleted(object arg) {
            if ((this.infoPagoDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoPagoDetalleCompleted(this, new infoPagoDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/insertHpagos", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertHpagos(string _nomina, string _correlativo) {
            object[] results = this.Invoke("insertHpagos", new object[] {
                        _nomina,
                        _correlativo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertHpagosAsync(string _nomina, string _correlativo) {
            this.insertHpagosAsync(_nomina, _correlativo, null);
        }
        
        /// <remarks/>
        public void insertHpagosAsync(string _nomina, string _correlativo, object userState) {
            if ((this.insertHpagosOperationCompleted == null)) {
                this.insertHpagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertHpagosOperationCompleted);
            }
            this.InvokeAsync("insertHpagos", new object[] {
                        _nomina,
                        _correlativo}, this.insertHpagosOperationCompleted, userState);
        }
        
        private void OninsertHpagosOperationCompleted(object arg) {
            if ((this.insertHpagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertHpagosCompleted(this, new insertHpagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/insertHpagosUgaDetalle", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertHpagosUgaDetalle(string _nomina, string _correlativo) {
            object[] results = this.Invoke("insertHpagosUgaDetalle", new object[] {
                        _nomina,
                        _correlativo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertHpagosUgaDetalleAsync(string _nomina, string _correlativo) {
            this.insertHpagosUgaDetalleAsync(_nomina, _correlativo, null);
        }
        
        /// <remarks/>
        public void insertHpagosUgaDetalleAsync(string _nomina, string _correlativo, object userState) {
            if ((this.insertHpagosUgaDetalleOperationCompleted == null)) {
                this.insertHpagosUgaDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertHpagosUgaDetalleOperationCompleted);
            }
            this.InvokeAsync("insertHpagosUgaDetalle", new object[] {
                        _nomina,
                        _correlativo}, this.insertHpagosUgaDetalleOperationCompleted, userState);
        }
        
        private void OninsertHpagosUgaDetalleOperationCompleted(object arg) {
            if ((this.insertHpagosUgaDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertHpagosUgaDetalleCompleted(this, new insertHpagosUgaDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/deletePagosUgaDetalle", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deletePagosUgaDetalle(string _nomina, string _correlativo) {
            object[] results = this.Invoke("deletePagosUgaDetalle", new object[] {
                        _nomina,
                        _correlativo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deletePagosUgaDetalleAsync(string _nomina, string _correlativo) {
            this.deletePagosUgaDetalleAsync(_nomina, _correlativo, null);
        }
        
        /// <remarks/>
        public void deletePagosUgaDetalleAsync(string _nomina, string _correlativo, object userState) {
            if ((this.deletePagosUgaDetalleOperationCompleted == null)) {
                this.deletePagosUgaDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletePagosUgaDetalleOperationCompleted);
            }
            this.InvokeAsync("deletePagosUgaDetalle", new object[] {
                        _nomina,
                        _correlativo}, this.deletePagosUgaDetalleOperationCompleted, userState);
        }
        
        private void OndeletePagosUgaDetalleOperationCompleted(object arg) {
            if ((this.deletePagosUgaDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletePagosUgaDetalleCompleted(this, new deletePagosUgaDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/facturas/deletePagosUga", RequestNamespace="http://galileo.edu/dynamicsax/facturas", ResponseNamespace="http://galileo.edu/dynamicsax/facturas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deletePagosUga(string _nomina, string _correlativo) {
            object[] results = this.Invoke("deletePagosUga", new object[] {
                        _nomina,
                        _correlativo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deletePagosUgaAsync(string _nomina, string _correlativo) {
            this.deletePagosUgaAsync(_nomina, _correlativo, null);
        }
        
        /// <remarks/>
        public void deletePagosUgaAsync(string _nomina, string _correlativo, object userState) {
            if ((this.deletePagosUgaOperationCompleted == null)) {
                this.deletePagosUgaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletePagosUgaOperationCompleted);
            }
            this.InvokeAsync("deletePagosUga", new object[] {
                        _nomina,
                        _correlativo}, this.deletePagosUgaOperationCompleted, userState);
        }
        
        private void OndeletePagosUgaOperationCompleted(object arg) {
            if ((this.deletePagosUgaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletePagosUgaCompleted(this, new deletePagosUgaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void agregarFacturaCompletedEventHandler(object sender, agregarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void validarFacturaCompletedEventHandler(object sender, validarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void infoBancariaDocenteCompletedEventHandler(object sender, infoBancariaDocenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoBancariaDocenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoBancariaDocenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void validaEsDocenteCompletedEventHandler(object sender, validaEsDocenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validaEsDocenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validaEsDocenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void infoPagoFacturacionCompletedEventHandler(object sender, infoPagoFacturacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoPagoFacturacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoPagoFacturacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void infoPagoDetalleCompletedEventHandler(object sender, infoPagoDetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoPagoDetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoPagoDetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertHpagosCompletedEventHandler(object sender, insertHpagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertHpagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertHpagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertHpagosUgaDetalleCompletedEventHandler(object sender, insertHpagosUgaDetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertHpagosUgaDetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertHpagosUgaDetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deletePagosUgaDetalleCompletedEventHandler(object sender, deletePagosUgaDetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deletePagosUgaDetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deletePagosUgaDetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deletePagosUgaCompletedEventHandler(object sender, deletePagosUgaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deletePagosUgaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deletePagosUgaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591