//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiciosDynamics.WebApi.WSInterfaceDyn {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSInterfaceDynamicsSoap", Namespace="http://galileo.edu/dynamicsax/")]
    public partial class WSInterfaceDynamics : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdDynCareersOperationCompleted;
        
        private System.Threading.SendOrPostCallback fotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdDynTorresSalonesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDatOraOperationCompleted;
        
        private System.Threading.SendOrPostCallback testConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback nuevoTutorDocenteDAXOperationCompleted;
        
        private System.Threading.SendOrPostCallback nuevoEmpleadoDynamicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarOperationCompleted;
        
        private System.Threading.SendOrPostCallback retTorresOperationCompleted;
        
        private System.Threading.SendOrPostCallback retSalonesOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambiaCuentaBancariaDocentesDAXOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoDocentesDAXOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerCorreoDocentesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CatedrativosFaltantesUGOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarrerasFaltantesUGOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSInterfaceDynamics() {
            this.Url = global::ServiciosDynamics.WebApi.Properties.Settings.Default.ServiciosDynamics_WebApi_WSInterfaceDyn_WSInterfaceDynamics;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdDynCareersCompletedEventHandler UpdDynCareersCompleted;
        
        /// <remarks/>
        public event fotoCompletedEventHandler fotoCompleted;
        
        /// <remarks/>
        public event UpdDynTorresSalonesCompletedEventHandler UpdDynTorresSalonesCompleted;
        
        /// <remarks/>
        public event GetDatOraCompletedEventHandler GetDatOraCompleted;
        
        /// <remarks/>
        public event testConnectionCompletedEventHandler testConnectionCompleted;
        
        /// <remarks/>
        public event nuevoTutorDocenteDAXCompletedEventHandler nuevoTutorDocenteDAXCompleted;
        
        /// <remarks/>
        public event nuevoEmpleadoDynamicsCompletedEventHandler nuevoEmpleadoDynamicsCompleted;
        
        /// <remarks/>
        public event obtenerNombreCompletedEventHandler obtenerNombreCompleted;
        
        /// <remarks/>
        public event BuscarCompletedEventHandler BuscarCompleted;
        
        /// <remarks/>
        public event CargarCompletedEventHandler CargarCompleted;
        
        /// <remarks/>
        public event GuardarCompletedEventHandler GuardarCompleted;
        
        /// <remarks/>
        public event retTorresCompletedEventHandler retTorresCompleted;
        
        /// <remarks/>
        public event retSalonesCompletedEventHandler retSalonesCompleted;
        
        /// <remarks/>
        public event cambiaCuentaBancariaDocentesDAXCompletedEventHandler cambiaCuentaBancariaDocentesDAXCompleted;
        
        /// <remarks/>
        public event infoDocentesDAXCompletedEventHandler infoDocentesDAXCompleted;
        
        /// <remarks/>
        public event obtenerCorreoDocentesCompletedEventHandler obtenerCorreoDocentesCompleted;
        
        /// <remarks/>
        public event CatedrativosFaltantesUGCompletedEventHandler CatedrativosFaltantesUGCompleted;
        
        /// <remarks/>
        public event CarrerasFaltantesUGCompletedEventHandler CarrerasFaltantesUGCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/UpdDynCareers", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdDynCareers() {
            object[] results = this.Invoke("UpdDynCareers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdDynCareersAsync() {
            this.UpdDynCareersAsync(null);
        }
        
        /// <remarks/>
        public void UpdDynCareersAsync(object userState) {
            if ((this.UpdDynCareersOperationCompleted == null)) {
                this.UpdDynCareersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdDynCareersOperationCompleted);
            }
            this.InvokeAsync("UpdDynCareers", new object[0], this.UpdDynCareersOperationCompleted, userState);
        }
        
        private void OnUpdDynCareersOperationCompleted(object arg) {
            if ((this.UpdDynCareersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdDynCareersCompleted(this, new UpdDynCareersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/foto", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string foto(int _correlativo) {
            object[] results = this.Invoke("foto", new object[] {
                        _correlativo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fotoAsync(int _correlativo) {
            this.fotoAsync(_correlativo, null);
        }
        
        /// <remarks/>
        public void fotoAsync(int _correlativo, object userState) {
            if ((this.fotoOperationCompleted == null)) {
                this.fotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfotoOperationCompleted);
            }
            this.InvokeAsync("foto", new object[] {
                        _correlativo}, this.fotoOperationCompleted, userState);
        }
        
        private void OnfotoOperationCompleted(object arg) {
            if ((this.fotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fotoCompleted(this, new fotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/UpdDynTorresSalones", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UpdDynTorresSalones() {
            object[] results = this.Invoke("UpdDynTorresSalones", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UpdDynTorresSalonesAsync() {
            this.UpdDynTorresSalonesAsync(null);
        }
        
        /// <remarks/>
        public void UpdDynTorresSalonesAsync(object userState) {
            if ((this.UpdDynTorresSalonesOperationCompleted == null)) {
                this.UpdDynTorresSalonesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdDynTorresSalonesOperationCompleted);
            }
            this.InvokeAsync("UpdDynTorresSalones", new object[0], this.UpdDynTorresSalonesOperationCompleted, userState);
        }
        
        private void OnUpdDynTorresSalonesOperationCompleted(object arg) {
            if ((this.UpdDynTorresSalonesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdDynTorresSalonesCompleted(this, new UpdDynTorresSalonesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/GetDatOra", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDatOra() {
            object[] results = this.Invoke("GetDatOra", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDatOraAsync() {
            this.GetDatOraAsync(null);
        }
        
        /// <remarks/>
        public void GetDatOraAsync(object userState) {
            if ((this.GetDatOraOperationCompleted == null)) {
                this.GetDatOraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatOraOperationCompleted);
            }
            this.InvokeAsync("GetDatOra", new object[0], this.GetDatOraOperationCompleted, userState);
        }
        
        private void OnGetDatOraOperationCompleted(object arg) {
            if ((this.GetDatOraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatOraCompleted(this, new GetDatOraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/testConnection", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string testConnection() {
            object[] results = this.Invoke("testConnection", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testConnectionAsync() {
            this.testConnectionAsync(null);
        }
        
        /// <remarks/>
        public void testConnectionAsync(object userState) {
            if ((this.testConnectionOperationCompleted == null)) {
                this.testConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestConnectionOperationCompleted);
            }
            this.InvokeAsync("testConnection", new object[0], this.testConnectionOperationCompleted, userState);
        }
        
        private void OntestConnectionOperationCompleted(object arg) {
            if ((this.testConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testConnectionCompleted(this, new testConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/nuevoTutorDocenteDAX", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string nuevoTutorDocenteDAX(string _orig, string _nit, string _nombre, string _codigo, bool _nacional) {
            object[] results = this.Invoke("nuevoTutorDocenteDAX", new object[] {
                        _orig,
                        _nit,
                        _nombre,
                        _codigo,
                        _nacional});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevoTutorDocenteDAXAsync(string _orig, string _nit, string _nombre, string _codigo, bool _nacional) {
            this.nuevoTutorDocenteDAXAsync(_orig, _nit, _nombre, _codigo, _nacional, null);
        }
        
        /// <remarks/>
        public void nuevoTutorDocenteDAXAsync(string _orig, string _nit, string _nombre, string _codigo, bool _nacional, object userState) {
            if ((this.nuevoTutorDocenteDAXOperationCompleted == null)) {
                this.nuevoTutorDocenteDAXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevoTutorDocenteDAXOperationCompleted);
            }
            this.InvokeAsync("nuevoTutorDocenteDAX", new object[] {
                        _orig,
                        _nit,
                        _nombre,
                        _codigo,
                        _nacional}, this.nuevoTutorDocenteDAXOperationCompleted, userState);
        }
        
        private void OnnuevoTutorDocenteDAXOperationCompleted(object arg) {
            if ((this.nuevoTutorDocenteDAXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevoTutorDocenteDAXCompleted(this, new nuevoTutorDocenteDAXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/nuevoEmpleadoDynamics", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string nuevoEmpleadoDynamics(string _emplId, string _dpi, string _primerNombre, string _segundoNombre, string _primerApellido, string _segundoApellido, string _apellidoCasada, string _fechaNac, int _estadoCivil, int _sexo, string _paisNac, string _depNac, string _muniNac, string _depDpi, string _muniDpi) {
            object[] results = this.Invoke("nuevoEmpleadoDynamics", new object[] {
                        _emplId,
                        _dpi,
                        _primerNombre,
                        _segundoNombre,
                        _primerApellido,
                        _segundoApellido,
                        _apellidoCasada,
                        _fechaNac,
                        _estadoCivil,
                        _sexo,
                        _paisNac,
                        _depNac,
                        _muniNac,
                        _depDpi,
                        _muniDpi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevoEmpleadoDynamicsAsync(string _emplId, string _dpi, string _primerNombre, string _segundoNombre, string _primerApellido, string _segundoApellido, string _apellidoCasada, string _fechaNac, int _estadoCivil, int _sexo, string _paisNac, string _depNac, string _muniNac, string _depDpi, string _muniDpi) {
            this.nuevoEmpleadoDynamicsAsync(_emplId, _dpi, _primerNombre, _segundoNombre, _primerApellido, _segundoApellido, _apellidoCasada, _fechaNac, _estadoCivil, _sexo, _paisNac, _depNac, _muniNac, _depDpi, _muniDpi, null);
        }
        
        /// <remarks/>
        public void nuevoEmpleadoDynamicsAsync(
                    string _emplId, 
                    string _dpi, 
                    string _primerNombre, 
                    string _segundoNombre, 
                    string _primerApellido, 
                    string _segundoApellido, 
                    string _apellidoCasada, 
                    string _fechaNac, 
                    int _estadoCivil, 
                    int _sexo, 
                    string _paisNac, 
                    string _depNac, 
                    string _muniNac, 
                    string _depDpi, 
                    string _muniDpi, 
                    object userState) {
            if ((this.nuevoEmpleadoDynamicsOperationCompleted == null)) {
                this.nuevoEmpleadoDynamicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevoEmpleadoDynamicsOperationCompleted);
            }
            this.InvokeAsync("nuevoEmpleadoDynamics", new object[] {
                        _emplId,
                        _dpi,
                        _primerNombre,
                        _segundoNombre,
                        _primerApellido,
                        _segundoApellido,
                        _apellidoCasada,
                        _fechaNac,
                        _estadoCivil,
                        _sexo,
                        _paisNac,
                        _depNac,
                        _muniNac,
                        _depDpi,
                        _muniDpi}, this.nuevoEmpleadoDynamicsOperationCompleted, userState);
        }
        
        private void OnnuevoEmpleadoDynamicsOperationCompleted(object arg) {
            if ((this.nuevoEmpleadoDynamicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevoEmpleadoDynamicsCompleted(this, new nuevoEmpleadoDynamicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/obtenerNombre", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerNombre(string _emplId) {
            object[] results = this.Invoke("obtenerNombre", new object[] {
                        _emplId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerNombreAsync(string _emplId) {
            this.obtenerNombreAsync(_emplId, null);
        }
        
        /// <remarks/>
        public void obtenerNombreAsync(string _emplId, object userState) {
            if ((this.obtenerNombreOperationCompleted == null)) {
                this.obtenerNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerNombreOperationCompleted);
            }
            this.InvokeAsync("obtenerNombre", new object[] {
                        _emplId}, this.obtenerNombreOperationCompleted, userState);
        }
        
        private void OnobtenerNombreOperationCompleted(object arg) {
            if ((this.obtenerNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerNombreCompleted(this, new obtenerNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/Buscar", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Buscar(string _txtBusqueda) {
            object[] results = this.Invoke("Buscar", new object[] {
                        _txtBusqueda});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAsync(string _txtBusqueda) {
            this.BuscarAsync(_txtBusqueda, null);
        }
        
        /// <remarks/>
        public void BuscarAsync(string _txtBusqueda, object userState) {
            if ((this.BuscarOperationCompleted == null)) {
                this.BuscarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarOperationCompleted);
            }
            this.InvokeAsync("Buscar", new object[] {
                        _txtBusqueda}, this.BuscarOperationCompleted, userState);
        }
        
        private void OnBuscarOperationCompleted(object arg) {
            if ((this.BuscarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCompleted(this, new BuscarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/Cargar", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Cargar(string Codigo) {
            object[] results = this.Invoke("Cargar", new object[] {
                        Codigo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CargarAsync(string Codigo) {
            this.CargarAsync(Codigo, null);
        }
        
        /// <remarks/>
        public void CargarAsync(string Codigo, object userState) {
            if ((this.CargarOperationCompleted == null)) {
                this.CargarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarOperationCompleted);
            }
            this.InvokeAsync("Cargar", new object[] {
                        Codigo}, this.CargarOperationCompleted, userState);
        }
        
        private void OnCargarOperationCompleted(object arg) {
            if ((this.CargarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarCompleted(this, new CargarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/Guardar", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Guardar(string Codigo, string Torre, string Oficina, string Extension) {
            this.Invoke("Guardar", new object[] {
                        Codigo,
                        Torre,
                        Oficina,
                        Extension});
        }
        
        /// <remarks/>
        public void GuardarAsync(string Codigo, string Torre, string Oficina, string Extension) {
            this.GuardarAsync(Codigo, Torre, Oficina, Extension, null);
        }
        
        /// <remarks/>
        public void GuardarAsync(string Codigo, string Torre, string Oficina, string Extension, object userState) {
            if ((this.GuardarOperationCompleted == null)) {
                this.GuardarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarOperationCompleted);
            }
            this.InvokeAsync("Guardar", new object[] {
                        Codigo,
                        Torre,
                        Oficina,
                        Extension}, this.GuardarOperationCompleted, userState);
        }
        
        private void OnGuardarOperationCompleted(object arg) {
            if ((this.GuardarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/retTorres", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet retTorres() {
            object[] results = this.Invoke("retTorres", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void retTorresAsync() {
            this.retTorresAsync(null);
        }
        
        /// <remarks/>
        public void retTorresAsync(object userState) {
            if ((this.retTorresOperationCompleted == null)) {
                this.retTorresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretTorresOperationCompleted);
            }
            this.InvokeAsync("retTorres", new object[0], this.retTorresOperationCompleted, userState);
        }
        
        private void OnretTorresOperationCompleted(object arg) {
            if ((this.retTorresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retTorresCompleted(this, new retTorresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/retSalones", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet retSalones(string _torre) {
            object[] results = this.Invoke("retSalones", new object[] {
                        _torre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void retSalonesAsync(string _torre) {
            this.retSalonesAsync(_torre, null);
        }
        
        /// <remarks/>
        public void retSalonesAsync(string _torre, object userState) {
            if ((this.retSalonesOperationCompleted == null)) {
                this.retSalonesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretSalonesOperationCompleted);
            }
            this.InvokeAsync("retSalones", new object[] {
                        _torre}, this.retSalonesOperationCompleted, userState);
        }
        
        private void OnretSalonesOperationCompleted(object arg) {
            if ((this.retSalonesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retSalonesCompleted(this, new retSalonesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/cambiaCuentaBancariaDocentesDAX", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cambiaCuentaBancariaDocentesDAX(string _nit, string _codigo, string _banco, string _tipoCuenta, string _numeroCuenta, string _usuarioOracle) {
            object[] results = this.Invoke("cambiaCuentaBancariaDocentesDAX", new object[] {
                        _nit,
                        _codigo,
                        _banco,
                        _tipoCuenta,
                        _numeroCuenta,
                        _usuarioOracle});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cambiaCuentaBancariaDocentesDAXAsync(string _nit, string _codigo, string _banco, string _tipoCuenta, string _numeroCuenta, string _usuarioOracle) {
            this.cambiaCuentaBancariaDocentesDAXAsync(_nit, _codigo, _banco, _tipoCuenta, _numeroCuenta, _usuarioOracle, null);
        }
        
        /// <remarks/>
        public void cambiaCuentaBancariaDocentesDAXAsync(string _nit, string _codigo, string _banco, string _tipoCuenta, string _numeroCuenta, string _usuarioOracle, object userState) {
            if ((this.cambiaCuentaBancariaDocentesDAXOperationCompleted == null)) {
                this.cambiaCuentaBancariaDocentesDAXOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambiaCuentaBancariaDocentesDAXOperationCompleted);
            }
            this.InvokeAsync("cambiaCuentaBancariaDocentesDAX", new object[] {
                        _nit,
                        _codigo,
                        _banco,
                        _tipoCuenta,
                        _numeroCuenta,
                        _usuarioOracle}, this.cambiaCuentaBancariaDocentesDAXOperationCompleted, userState);
        }
        
        private void OncambiaCuentaBancariaDocentesDAXOperationCompleted(object arg) {
            if ((this.cambiaCuentaBancariaDocentesDAXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambiaCuentaBancariaDocentesDAXCompleted(this, new cambiaCuentaBancariaDocentesDAXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/infoDocentesDAX", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DocenteDAX[] infoDocentesDAX(string _codPers) {
            object[] results = this.Invoke("infoDocentesDAX", new object[] {
                        _codPers});
            return ((DocenteDAX[])(results[0]));
        }
        
        /// <remarks/>
        public void infoDocentesDAXAsync(string _codPers) {
            this.infoDocentesDAXAsync(_codPers, null);
        }
        
        /// <remarks/>
        public void infoDocentesDAXAsync(string _codPers, object userState) {
            if ((this.infoDocentesDAXOperationCompleted == null)) {
                this.infoDocentesDAXOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoDocentesDAXOperationCompleted);
            }
            this.InvokeAsync("infoDocentesDAX", new object[] {
                        _codPers}, this.infoDocentesDAXOperationCompleted, userState);
        }
        
        private void OninfoDocentesDAXOperationCompleted(object arg) {
            if ((this.infoDocentesDAXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoDocentesDAXCompleted(this, new infoDocentesDAXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/obtenerCorreoDocentes", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void obtenerCorreoDocentes() {
            this.Invoke("obtenerCorreoDocentes", new object[0]);
        }
        
        /// <remarks/>
        public void obtenerCorreoDocentesAsync() {
            this.obtenerCorreoDocentesAsync(null);
        }
        
        /// <remarks/>
        public void obtenerCorreoDocentesAsync(object userState) {
            if ((this.obtenerCorreoDocentesOperationCompleted == null)) {
                this.obtenerCorreoDocentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerCorreoDocentesOperationCompleted);
            }
            this.InvokeAsync("obtenerCorreoDocentes", new object[0], this.obtenerCorreoDocentesOperationCompleted, userState);
        }
        
        private void OnobtenerCorreoDocentesOperationCompleted(object arg) {
            if ((this.obtenerCorreoDocentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerCorreoDocentesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/CatedrativosFaltantesUG", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CatedrativosFaltantesUG(string fecha, string origen) {
            object[] results = this.Invoke("CatedrativosFaltantesUG", new object[] {
                        fecha,
                        origen});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CatedrativosFaltantesUGAsync(string fecha, string origen) {
            this.CatedrativosFaltantesUGAsync(fecha, origen, null);
        }
        
        /// <remarks/>
        public void CatedrativosFaltantesUGAsync(string fecha, string origen, object userState) {
            if ((this.CatedrativosFaltantesUGOperationCompleted == null)) {
                this.CatedrativosFaltantesUGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCatedrativosFaltantesUGOperationCompleted);
            }
            this.InvokeAsync("CatedrativosFaltantesUG", new object[] {
                        fecha,
                        origen}, this.CatedrativosFaltantesUGOperationCompleted, userState);
        }
        
        private void OnCatedrativosFaltantesUGOperationCompleted(object arg) {
            if ((this.CatedrativosFaltantesUGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CatedrativosFaltantesUGCompleted(this, new CatedrativosFaltantesUGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://galileo.edu/dynamicsax/CarrerasFaltantesUG", RequestNamespace="http://galileo.edu/dynamicsax/", ResponseNamespace="http://galileo.edu/dynamicsax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CarrerasFaltantesUG(string fecha, string origen) {
            object[] results = this.Invoke("CarrerasFaltantesUG", new object[] {
                        fecha,
                        origen});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CarrerasFaltantesUGAsync(string fecha, string origen) {
            this.CarrerasFaltantesUGAsync(fecha, origen, null);
        }
        
        /// <remarks/>
        public void CarrerasFaltantesUGAsync(string fecha, string origen, object userState) {
            if ((this.CarrerasFaltantesUGOperationCompleted == null)) {
                this.CarrerasFaltantesUGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarrerasFaltantesUGOperationCompleted);
            }
            this.InvokeAsync("CarrerasFaltantesUG", new object[] {
                        fecha,
                        origen}, this.CarrerasFaltantesUGOperationCompleted, userState);
        }
        
        private void OnCarrerasFaltantesUGOperationCompleted(object arg) {
            if ((this.CarrerasFaltantesUGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarrerasFaltantesUGCompleted(this, new CarrerasFaltantesUGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://galileo.edu/dynamicsax/")]
    public partial class DocenteDAX {
        
        private string nitField;
        
        private string nombreField;
        
        private string codTutorField;
        
        private string codProveedorField;
        
        private string formaPagoField;
        
        private string codigoBancoField;
        
        private string codigoTipoBancoField;
        
        private string numeroCuentaField;
        
        /// <remarks/>
        public string Nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string CodTutor {
            get {
                return this.codTutorField;
            }
            set {
                this.codTutorField = value;
            }
        }
        
        /// <remarks/>
        public string CodProveedor {
            get {
                return this.codProveedorField;
            }
            set {
                this.codProveedorField = value;
            }
        }
        
        /// <remarks/>
        public string FormaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBanco {
            get {
                return this.codigoBancoField;
            }
            set {
                this.codigoBancoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoTipoBanco {
            get {
                return this.codigoTipoBancoField;
            }
            set {
                this.codigoTipoBancoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdDynCareersCompletedEventHandler(object sender, UpdDynCareersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdDynCareersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdDynCareersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void fotoCompletedEventHandler(object sender, fotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdDynTorresSalonesCompletedEventHandler(object sender, UpdDynTorresSalonesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdDynTorresSalonesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdDynTorresSalonesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDatOraCompletedEventHandler(object sender, GetDatOraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatOraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatOraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void testConnectionCompletedEventHandler(object sender, testConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void nuevoTutorDocenteDAXCompletedEventHandler(object sender, nuevoTutorDocenteDAXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevoTutorDocenteDAXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevoTutorDocenteDAXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void nuevoEmpleadoDynamicsCompletedEventHandler(object sender, nuevoEmpleadoDynamicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevoEmpleadoDynamicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevoEmpleadoDynamicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerNombreCompletedEventHandler(object sender, obtenerNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarCompletedEventHandler(object sender, BuscarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CargarCompletedEventHandler(object sender, CargarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GuardarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void retTorresCompletedEventHandler(object sender, retTorresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retTorresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retTorresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void retSalonesCompletedEventHandler(object sender, retSalonesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retSalonesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retSalonesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cambiaCuentaBancariaDocentesDAXCompletedEventHandler(object sender, cambiaCuentaBancariaDocentesDAXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambiaCuentaBancariaDocentesDAXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambiaCuentaBancariaDocentesDAXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void infoDocentesDAXCompletedEventHandler(object sender, infoDocentesDAXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoDocentesDAXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoDocentesDAXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocenteDAX[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocenteDAX[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerCorreoDocentesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CatedrativosFaltantesUGCompletedEventHandler(object sender, CatedrativosFaltantesUGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CatedrativosFaltantesUGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CatedrativosFaltantesUGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CarrerasFaltantesUGCompletedEventHandler(object sender, CarrerasFaltantesUGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarrerasFaltantesUGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarrerasFaltantesUGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591