//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiciosDynamics.WebApi.WSDocentes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSDocentesSoap", Namespace="http://tempuri.org/")]
    public partial class WSDocentes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback nuevoTutorDocenteDAXOperationCompleted;
        
        private System.Threading.SendOrPostCallback exiteDocenteDynamicsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSDocentes() {
            this.Url = global::ServiciosDynamics.WebApi.Properties.Settings.Default.ServiciosDynamics_WebApi_WSDocentes_WSDocentes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event nuevoTutorDocenteDAXCompletedEventHandler nuevoTutorDocenteDAXCompleted;
        
        /// <remarks/>
        public event exiteDocenteDynamicsCompletedEventHandler exiteDocenteDynamicsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nuevoTutorDocenteDAX", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string nuevoTutorDocenteDAX(string _orig, string _nit, string _nombre, string _codigo, bool _nacional, string _usuarioOracle) {
            object[] results = this.Invoke("nuevoTutorDocenteDAX", new object[] {
                        _orig,
                        _nit,
                        _nombre,
                        _codigo,
                        _nacional,
                        _usuarioOracle});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevoTutorDocenteDAXAsync(string _orig, string _nit, string _nombre, string _codigo, bool _nacional, string _usuarioOracle) {
            this.nuevoTutorDocenteDAXAsync(_orig, _nit, _nombre, _codigo, _nacional, _usuarioOracle, null);
        }
        
        /// <remarks/>
        public void nuevoTutorDocenteDAXAsync(string _orig, string _nit, string _nombre, string _codigo, bool _nacional, string _usuarioOracle, object userState) {
            if ((this.nuevoTutorDocenteDAXOperationCompleted == null)) {
                this.nuevoTutorDocenteDAXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevoTutorDocenteDAXOperationCompleted);
            }
            this.InvokeAsync("nuevoTutorDocenteDAX", new object[] {
                        _orig,
                        _nit,
                        _nombre,
                        _codigo,
                        _nacional,
                        _usuarioOracle}, this.nuevoTutorDocenteDAXOperationCompleted, userState);
        }
        
        private void OnnuevoTutorDocenteDAXOperationCompleted(object arg) {
            if ((this.nuevoTutorDocenteDAXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevoTutorDocenteDAXCompleted(this, new nuevoTutorDocenteDAXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/exiteDocenteDynamics", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool exiteDocenteDynamics(string _nit) {
            object[] results = this.Invoke("exiteDocenteDynamics", new object[] {
                        _nit});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void exiteDocenteDynamicsAsync(string _nit) {
            this.exiteDocenteDynamicsAsync(_nit, null);
        }
        
        /// <remarks/>
        public void exiteDocenteDynamicsAsync(string _nit, object userState) {
            if ((this.exiteDocenteDynamicsOperationCompleted == null)) {
                this.exiteDocenteDynamicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexiteDocenteDynamicsOperationCompleted);
            }
            this.InvokeAsync("exiteDocenteDynamics", new object[] {
                        _nit}, this.exiteDocenteDynamicsOperationCompleted, userState);
        }
        
        private void OnexiteDocenteDynamicsOperationCompleted(object arg) {
            if ((this.exiteDocenteDynamicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exiteDocenteDynamicsCompleted(this, new exiteDocenteDynamicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void nuevoTutorDocenteDAXCompletedEventHandler(object sender, nuevoTutorDocenteDAXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevoTutorDocenteDAXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevoTutorDocenteDAXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void exiteDocenteDynamicsCompletedEventHandler(object sender, exiteDocenteDynamicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exiteDocenteDynamicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exiteDocenteDynamicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591